input_vcf: 'test_trio.vcf.gz'
freebayes_vcf: 'TRUE' # TRUE if using freebayes vcf. vt slightly different for freebayes.
aaf_change: '1.1'
output_type: ['geminiDB', 'family_query', 'individual_query'] #list, delete the compopnent that is not needed.
family_name: [] # empty list or One or more family names in the list ['family_1', 'family_2']. If it's blank and output_type includes family_query, then it will take ped file and make a family list.
ped: 'test_trio.ped' # has to be \t delimited.
regions: '/home/$USER/git/variant_prioritization/src/vcf_region_split_1_coords.txt'
#regions, 1 for panel (only 1,2,..,22,x,y)
#regions, 25 or 100 for WGS of 50 cases.
datatype: 'panel' #panel, exome, wgs, blank; currently, only "panel" is meaningful
pick: 'canonical'
LAFplot: 'TRUE' #If TRUE then chromosome LesserAlleleFreq plot will be generated. Any other value equals to FALSE
samtools_version: 'samtools/1.9'
ref_genome: '/data/OGVFB/resources/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/99'
vcfanno_version: 'vcfanno/0.2.9'
vcfanno_lua: '/home/$USER/git/variant_prioritization/src/vcfanno_custom.lua'
vcfanno_conf: '/home/$USER/git/variant_prioritization/src/vcfanno_v4.conf'
vcf2db_version: 'vcf2db/2018.10.26' #'vcf2db/2017.12.11'
gemini_version: 'gemini/0.20.1'
peddy_version: 'peddy/0.3.1'
python2_version: 'python/2.7'
R_version: 'R/3.6.3'
vt_version: 'vt/0.57721'
spliceai_version: 'spliceai/1.3'
spliceai_wrapper: 'FALSE' #any value other than TRUE will run spliceai directly
spliceai-wrapper_version: 'spliceai-wrapper/0.1.0'
VCF-kit_version: 'VCF-kit/0.1.6'
annovar_version: 'annovar/2019-10-24'
InterVar_version: 'intervar/2.1.2'
intervar_evidence: '/data/OGVFB/OGL_NGS/OGL.variants.evidence.txt'
intervar_Rscript_path: '/home/$USER/git/variant_prioritization/src/intervar_v1.8.R'
OGL_Dx_research_genes: '/data/OGVFB/OGL_NGS/variant_prioritization/data/OGLv1_panel_DxORcandidate.tsv'
pandoc_version: 'pandoc/2.1.1'
gemini_lenient: 'Yes'
output_raw: 'Yes'
SeeGEM_script: '/home/$USER/git/variant_prioritization/src/GEMINI_db_to_SeeGEM_OGL.R'
HGMDtranscript: '/data/OGL/resources/HGMD/HGMDtranscript.txt'
#quotation marks can be single or doubl
##this is to force git to commit this file "OGL" added in the SeeGEM_script
