input_vcf: 'test_trio.vcf.gz' #bcf also accepted.
gatk3: 'FALSE' # FALSE if using freebayes or deepvariant vcf.
aaf_change: '1.1'
output_type: ['vcf', 'geminiDB', 'family_query', 'individual_query'] #list, delete the component that is not needed, 'vcf' or blank for annotating a vcf file only
NGS_genotype_calling: 'OGL' #OGL (default, inlcuding outputs other than SNV & small indel) OR vcf (only the vcf file is present)
family_name: [] # empty list or One or more family names in the list ['family_1', 'family_2']. If it's blank and output_type includes family_query, then it will take ped file and make a family list.
seeGEM: 'FALSE' #TRUE or FALSE
ped: 'example.ped' # has to be \t delimited. Keep as is and cp the example.ped for vcf annotation only
regions: '/home/$USER/git/variant_prioritization/src_hg38/vcf_region_split_chr_coords.txt' # hg19 version delete _hg38
#regions, 1 for panel (only 1,2,..,22,X); "chr" for exome if needed;
#regions, 25 or 100 for WGS of 50 cases. Use chr, 24, 99, 499 for genome.
datatype: 'exome' #panel, wes, exome, wgs, genome, blank
configuration_file: 'config_variant_prioritization.yaml'
genomeBuild: 'GRCh38' # GRCh37 or GRCh38, case sensitive
spliceai: 'spliceai' # choose from 'spliceai', 'vcfanno', or 'wrapper'; choose vcfanno if variants already added to the spliceai depot file.
pangolin: 'vcfanno' # choose from 'pangolin' 'vcfanno'; choose vcfanno if variants already added to the pangolin depot file. Pangolin error to be fixed
spliceai_version: 'spliceai/1.3.1' #version 1.3.1 seems to be mucher slower.Try to make spliceai_wrapper work if possible
spliceai-wrapper_version: 'spliceai-wrapper/0.1.0'
gemini_lenient: 'Yes'
pick: 'canonical' #pick, canonical, or all. See snake file for description
LAFplot: 'FALSE' #TRUE if panel after production. If TRUE then chromosome LesserAlleleFreq plot will be generated. Any other value equals to FALSE
samtools_version: 'samtools/1.17' #previous version 1.13 is still available, can go back if needed.
ref_genome: '' #hard-coded in snakemake file
VEP_version: 'VEP/107' #previous version 103, VEP/109 had error message
vcfanno_version: 'vcfanno/0.3.3'
vcfanno_lua: '/home/$USER/git/variant_prioritization/src_hg38/vcfanno_custom.lua' #hg19 version delete _hg38
vcfanno_conf: '' #hard-coded in snakemake file
vcf2db_version: 'vcf2db/2018.10.26' #'vcf2db/2020.09.14'
gemini_version: 'gemini/0.20.1' # 0.20.1
peddy_version: 'peddy/0.4.8'
python2_version: 'python/2.7' #no longer used
R_version: 'R/4.3.0' #3.6.3 no longer supported
vt_version: 'vt/0.57721'
VCF-kit_version: 'VCF-kit/0.2.9' #no longer used
annovar_version: 'annovar/2020-06-08' #previous ver 2019-10-24
InterVar_version: 'InterVar2.2.1' # OGL/resources/git hardcoded in Snakemake
hgmd_version: '2023.4'
annovar_clinvar_version: 'clinvar_20220320' #clinv is downloaded every run
pangolin-splice_version: 'pangolin-splice/1.0.1'
OGLexome_version: '/data/OGL/resources/OGLsample/OGL.exome.gl.fb.v2.2022-09.vcf.gz'
OGLgenome_version: '/data/OGL/resources/OGLsample/OGL.genome.gl.fb.v2.index.2022-09.vcf.gz'
ACMG_SF: 'v3.1'
manta_freq: '/data/OGL/resources/manta/manta.OGL.freq.2022-09.tsv' #make it an excel file with two sheets if using scramble-like db file
mastermind_vcf: '/data/OGL/resources/mastermind/mastermind_cited_variants_reference-2022.10.02-grch38.vcf.gz'
#intervar_evidence: '/data/OGVFB/OGL_NGS/OGL.variants.evidence.txt'
crossmap_version: 'crossmap/0.6.5'
intervar_Rscript_path: '/home/$USER/git/variant_prioritization/src_hg38/intervar_v1.8.R' # hg19 version delete _hg38
OGL_Dx_research_genes: '/data/OGL/resources/OGLpanelGeneDxORcandidate.xlsx'
pandoc_version: 'pandoc/2.1.1'
output_raw: 'Yes'
SeeGEM_script: '/home/$USER/git/variant_prioritization/src/GEMINI_db_to_SeeGEM_OGL.R' # not used
HGMDtranscript: '/data/OGL/resources/HGMD/HGMDtranscript.txt'
#quotation marks can be single or doubl
##this is to force git to commit this file "OGL" added in the SeeGEM_script
